### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Can't load the profile.

### ISSUE THREAD

**Issue by Giando** [andrewsyc/github-follow-bot#1]
Hello @andrewsyc,
I do not understand why, worked before, but now I get this error:

``` python
Traceback (most recent call last):
  File "./follow_bot.py", line 11, in <module>
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpE0H1jK If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

Thank you and congratulations for the project! :wink::+1:

**Comment by andrewsyc** [comment]
Giando, sorry I'm so negligent on reading issues. 

The best bet is to get the newest release of a selenium driver, or to run an older version of firefox (or any other browser you use). Whenever the browser is updated on the computer, I noticed that it breaks the script on occasion.
